#ARG Instruction 
FROM almalinux:9
ARG course="AWS Devops" \
    company="joindveops" \
    duration="4 months"
RUN echo "Course is: $course, Company is: $company, and Duration is: $duration"
CMD ["sleep", "100"]
